# Generated by Django 5.1.1 on 2024-10-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_delivery_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_id',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
